### ISSUE TITLE
Spb flag parser will bug out when trying to use /whois for a group ID

### ISSUE THREAD

**Issue by ALiwoto** [intellivoid/issues#4]
## What is the problem?
> This issue has already been mentioned several times, I just wanted to rewrite a summery and a proposal to solve for it.
Spam protect bot (SPB) commands work something like this:
`/whois 123456...` (the number is someone's ID)
`/l -f -r 0xSCAM`

The problem is that flags have single line `'-'`,
so if we use 
`/whois -12345...` (that number is a group ID)
the bot will think that we want to use a flag, and it won't show us the expecting result.

<hr/>

## How to reproduce?
Simply, enter the command `/whois -1001192616647` and you will see the bug.

<hr/>

## What did I expect to happen?
I expected to see the info about the group (since the API works just fine with this).

<hr/>

## What did happen instead?
It sent this message:
`Unable to resolve the query '1001192616647'!`.

<hr/>

## Proposals to fix this problem?
1. Before considering something as a "flag", check if the flag's name is completely an int or not (or even better, check if it starts with a digit or not), if it starts with a digit (or something else), then it's not a flag. So there is a rule here: `Flags should always start with a letter, not a number`. (this is my suggestions, since it needs a little bit changes in the code)
2. Don't use single prefixes for flags, instead use double prefix, like: `/l --f --r 0xSCAM` (or something like this?) <-- (tho I don't recommend this solution that much, since it needs a lot of changes in code compared to the first solution, but still it will work)

**Comment by Justasic** [comment]
Hello and thank you for bringing this to my attention.

I recently rewrote the flag parser to fix a great many bugs but had not gotten around to solving the problems with some of the commands in SpamProtectionBot. The problem was that the existing argument parsing code in the /whois command had not been updated with the new changes and did not fully understand the context of the arguments provided.

I have made the changes to the code which now allow for nearly any variation of the commands:
```
/whois
/whois -p
/whois -c
/whois -p -c
/whois -c -p
/whois -c --private
/whois --private -c
/whois --private --chat
/whois -p --chat
/whois -c -1001255696810
/whois -c -1001255696810 -p
/whois -p -c -1001255696810
/whois --private -c -1001255696810
/whois --chat="-1001255696810"
/whois --chat=-1001255696810
/whois --chat="-1001255696810" -p
/whois --chat="-1001255696810" --private
/whois --private --chat="-1001255696810"
/whois -p --chat="-1001255696810"
```
I tested with all these variations and I believe this issue is now solved, please re-open this issue with an updated example if you find a combination which fails or exhibits incorrect behavior.

**Comment by ALiwoto** [comment]
Oh nice
`--chat="-1001255696810"` is a really nice idea

and thank you for responding!
